version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fakeNewsDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
